CONFIG_ZMK_KEYBOARD_NAME="nano-joy"
CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_BLE=y
CONFIG_I2C=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_ADS1015_INPUT=y
CONFIG_ZMK_ADS1015_INPUT_LOG_LEVEL=3

# zmk-hid-io joystick
CONFIG_USB_DEVICE_HID=y
CONFIG_USB_HID_DEVICE_COUNT=2
CONFIG_ZMK_HID_IO=y
CONFIG_ZMK_HID_IO_JOYSTICK=y

# TPS43 touchpad
CONFIG_ZMK_TPS43_INPUT=y
CONFIG_ZMK_TPS43_INPUT_TAPDRAG=y
CONFIG_ZMK_TPS43_INPUT_TAP_TIMEOUT_MS=180
CONFIG_ZMK_TPS43_INPUT_DOUBLE_CLICK_TIMEOUT_MS=250
CONFIG_ZMK_TPS43_INPUT_TAP_MOVE_THRESH=30
CONFIG_ZMK_TPS43_INPUT_SAME_SPOT_THRESH=80
CONFIG_ZMK_TPS43_INPUT_DROP_GRACE_MS=20
CONFIG_ZMK_TPS43_INPUT_EDGESCROLL=y
CONFIG_ZMK_TPS43_INPUT_EDGE_RIGHT_PCT=15
CONFIG_ZMK_TPS43_INPUT_EDGE_BOTTOM_PCT=15
CONFIG_ZMK_TPS43_INPUT_SENSITIVITY_NUM=1
CONFIG_ZMK_TPS43_INPUT_SENSITIVITY_DENOM=2
CONFIG_ZMK_TPS43_INPUT_LOG_LEVEL=3

# Debug: global log level
CONFIG_LOG_DEFAULT_LEVEL=0
